/** Shared application state */
export const state = {
    hosts: [],
    activeSessions: [],
    historySessions: [],
    auditEntries: [],
    sshKeys: [],
    currentUser: null,
    allUsers: [],
    editingHostId: null,
    terminals: new Map(),
    activeTabId: null,
    tabCounter: 0,
    allGroups: [],
    msSelectedHosts: new Set(),
    msDropdownOpen: false,
    allGroupMappings: [],
    // Session viewer
    svTerm: null,
    svFitAddon: null,
    svEvents: [],
    svTotalTime: 0,
    svPlaying: false,
    svSpeed: 1,
    svPosition: 0,
    svTimerId: null,
    svCancelled: false,
    svWs: null,
    svLive: false,
    svLiveStart: null,
    svLiveTicker: null,
    svLiveTranscriptBuf: '',
};
